#docker access token: fa16a9c1-684b-47c0-834f-ce477f06cf8b

name: ci
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest	  
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        #uses: docker/login-action@v1
        #with:
        #  username: ${{ secrets.DOCKER_HUB_USERNAME }}
        #  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multiple-branche-app:latest
          tags: ghcr.io/mthiand/multiple-branche-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/multiple-branche-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/multiple-branche-app:buildcache,mode=max

